import { Inter } from 'next/font/google'
import './globals.css'
import HeaderBanas from './Components/HeaderBanas'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Umang Mall Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderBanas/>{children}</body>
    </html>
  )
}
